first component without EventListeners
js-tasks-ru/js-20230223_valerii-sklyarov pull request #6
Opened 2023-03-09 14:30 UTC by valeriiSkliar

I wanted to submit my solution for review before class started.
In a hurry:
- didn't delete some comments
- did not remove the Tets method
- not enough time to make EventListeners
- and also changed the system files a little, but only the formatting.

2023-03-09 14:32 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-11 13:09 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  constructor({data = [], label = '', link, value,formatHeading = data => `${data}`} = {}) {
у параметров `link` и `value` было бы неплохо также задать значения по умолчанию

2023-03-11 13:09 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    this.chartHeight = 50;
старайтесь не загромождать конструктор св-вами к-е не зависят от входящих значений

2023-03-11 13:09 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      return `<div class="column-chart column-chart_loading" style="--chart-height: 50">
что такое 50?

2023-03-11 13:10 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    if (this.data.length === 0) {
в не зависимости от того `this.data` имеет длину или нет, мы возвращаем данный шаблон и конструируем компонент

2023-03-11 13:11 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      return `<div class="column-chart column-chart_loading" style="--chart-height: 50">
а вот что зависит от длины `this.data` так это наличие или отсутствие класса `column-chart_loading`

2023-03-11 13:11 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    const columns = this.data.map(item => {
Этой логики не должно быть в данном методе, следует вынести в отдельный

2023-03-11 13:12 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    return `<div class="column-chart" style="--chart-height: 50">
Этот дубликат шаблона следует устранить

2023-03-11 13:12 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +  initEventListeners() {
метод удалить, в данном решении он не нужен

2023-03-11 13:12 UTC, dosandk requested changes
посмотрите коменты, внесите правки

2023-03-15 16:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-15 18:14 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-15 18:22 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-03-16 14:23 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  static activeNotification;
good 👍

2023-03-16 14:24 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    let content = '';
зачем переменная объявлена тут?
почему не внутри `map`?

2023-03-16 14:24 UTC, dosandk approved these changes
good 👍

2023-03-16 14:25 UTC, merged